### PR TITLE
Norel and nodelog parsers

### LINKED ISSUE #2: Create a NoRel parser module

### LINKED ISSUE #6: Create a tree search / node log parser module

### PR DESCRIPTION
**Pull request by simonbowly**
Closes #2
Closes #6 

@maliheha can you review this one? Added classes/module for norel and the nodelog. Slightly different API/test pattern to #8, hopefully we can converge on a common pattern.

### CODE REVIEW

**Comment by simonbowly** [comment]
Weirdly the tests are all passing locally (3.8 onwards). I guess the regression test is a bit finicky, but eventually that will be removed anyway.

**Comment by simonbowly** [comment]
Btw, I wound up back at logstart/parse in this case, but it's not set in stone. I was looking at the ParserFlag enum and thinking maybe a boolean return from the start & parse methods is sufficient? This makes the outer loop:

```
def parse_lines(parser, loglines):
    it = iter(loglines)
    for line in it:
        if self.log_start(line):
            # Once the parser indicates start, send lines to it
            # until it indicates stop.
            for line in it:
                continue_ = self.parse(line)
                if not continue_:
                    return
```

**Comment by maliheha** [comment]
> Btw, I wound up back at logstart/parse in this case, but it's not set in stone. I was looking at the ParserFlag enum and thinking maybe a boolean return from the start & parse methods is sufficient? This makes the outer loop:
> 
> ```
> def parse_lines(parser, loglines):
>     it = iter(loglines)
>     for line in it:
>         if self.log_start(line):
>             # Once the parser indicates start, send lines to it
>             # until it indicates stop.
>             for line in it:
>                 continue_ = self.parse(line)
>                 if not continue_:
>                     return
> ```

I am so sorry for painfully being slow on this. 

I think before going through the code for detailed review, we need to agree on the overall design. I had a look over your PR and it seems to me that we can converge to the following design:
- Get rid of "Enum" class completely. This was desirable from the start to me because it allows to have an internal state for each parser. However, I agree that it seems that we do not need this and a simple boolean flag would be sufficient!
- Each parser has two main methods of `start_parsing(line)`, `continue_parsing(line)` that return a boolean flag. I guess all parsers would have the method `get_summary()` but not `get_progress()`. 
- I still think that the main loop should look like your original proposal discussed on Teams before. I think the method `continue_parsing()` likely does not even need to have a return. We know that even if this method returns False, it does not mean that we are done with the parser. For example, we see lines starting with "**Found phase-1 solution: relaxation**" in the NoRelHeur part of the log. However, we are not including a regular expression for this line and upon passing this line, we will return False which is not an indication of being done with parsing the NoRel logging. So, your previous comment about the start of another parser should indicate the end of the current parser is valid.
- We also need to agree on the coding style. I am using Google Style and black for docstring/comments and formatting. I am happy to switch to something else if you like another style. The important thing is that we both use the same style.
- I am pretty much used to python unittest module for writing tests. I would not be worried about how the tests are implemented too much as long as there are tests and they are picked up by running `pytest` from the main folder. 

I think it would be best if we both agree on the above points. We can then polish the PRs given what we agree on and then submit for review. Please let me know what you think.

We can also meet if you think we can converge faster.

**Comment by simonbowly** [comment]
Sounds good, thanks!

> We know that even if this method returns False, it does not mean that we are done with the parser.

I would only return False if the parser can sensibly be aware that the end of it's log has been reached without borrowing regexes from another module (often it cannot, and that's also fine, it should always return true). For norel, it should always return true (not false for unrecognised lines). For the node log, there is a detectable termination line, so it could return false to indicate it should never be called again. We may wind up ignoring this return and/or most classes might just always return True, but I think we should keep it.

So then the general skeleton would be:

```python
class SomeParser:
    def start_parsing(self, line: str) -> bool:
        return False   # indicates start_parsing should be called with the next log line 
        return True    # indicates continue_parsing should be called for all future lines
    def continue_parsing(self, line: str) -> bool:
        return True    # continue_parsing should be called with the next log line
        return False   # this parser should not receive any future lines
```

Happy to go with black + google style + mix of pytest/unittest frameworks. We should add a contributing.md file & perhaps a pre-commit config to help us stick to it. It would be easier I think to meet and put all the pieces into place on the one branch.

**Pull request merged**
